"theme-bootstrap-3" :
  "use" : "theme"

asset_pipeline:
  enable: false

posts :
  stop_at_header: false # default is false
  summary_lines : 1  # default is 20

"date_format": "%B %d, %Y"

"pages" :
  "sort" : ["date", "desc"]